# Generated by Django 5.2.7 on 2025-11-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='qualification',
            field=models.CharField(max_length=200, verbose_name='Лицензия'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='work_experience',
            field=models.PositiveIntegerField(verbose_name='Опыт работы'),
        ),
    ]
