# Generated by Django 5.2.7 on 2025-11-12 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coach_education_alter_coach_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='coach',
            name='work_start_year',
            field=models.IntegerField(blank=True, help_text='Год начала работы тренером', null=True, validators=[django.core.validators.MinValueValidator(1950, message='Год не может быть раньше 1950'), django.core.validators.MaxValueValidator(2025, message='Год не может быть больше текущего')], verbose_name='Опыт работы (с года)'),
        ),
    ]
