# Generated by Django 5.2.7 on 2025-11-13 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_coach_work_experience_coach_work_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_full_name', models.CharField(max_length=200, verbose_name='ФИО родителя')),
                ('parent_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('child_full_name', models.CharField(max_length=200, verbose_name='ФИО ребенка')),
                ('child_birth_date', models.DateField(verbose_name='Дата рождения ребенка')),
                ('branch', models.CharField(choices=[('kolomenskaya', 'Коломенская'), ('tsaritsyno', 'Царицино')], max_length=50, verbose_name='Отделение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]


