# Generated by Django 5.2.7 on 2025-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_joinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinRequest',
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['order', 'full_name'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='coach',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
