# Generated by Django 5.2.7 on 2025-11-17 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_joinrequest_alter_coach_options_coach_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_full_name', models.CharField(max_length=200, verbose_name='ФИО родителя')),
                ('parent_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Контактный телефон')),
                ('child_full_name', models.CharField(max_length=200, verbose_name='ФИО ребёнка')),
                ('child_birth_date', models.DateField(verbose_name='Дата рождения ребёнка')),
                ('branch', models.CharField(choices=[('centr', 'Центр'), ('sever', 'Север'), ('yug', 'Юг')], max_length=100, verbose_name='Отделение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на тренировку',
                'verbose_name_plural': 'Заявки на тренировку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
