# Generated by Django 5.2.7 on 2025-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_joinrequest_delete_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='branch',
            field=models.CharField(choices=[('', 'Выбрать отделение'), ('centr', 'Царицыно'), ('sever', 'Коломенская')], max_length=100, verbose_name='Отделение'),
        ),
    ]
